### ISSUE TITLE
Does not work with SBT 1.2.3

### ISSUE THREAD

**Issue by ngocdaothanh** [scalate/sbt-scalate-precompiler#10]
I've created this very simple example project:
https://github.com/xitrum-framework/sbt-scalate-precompiler-example

sbt-scalate-precompiler works when the project is set to use SBT 0.13.7.

But it doesn't work when the project is set to use SBT 1.2.3.

**Comment by ngocdaothanh** [comment]
Note: I'm using Mac 10.13.6.

**Comment by ngocdaothanh** [comment]
I've just checked on Ubuntu.
sbt-scalate-precompiler does not work with SBT 1.2.3 either.

**Comment by ngocdaothanh** [comment]
I've just tried with SBT 1.1.0. It doesn't work either.

When I tried with SBT 1.0.0, there's error with SBT:

```
[error] sbt.internal.IncompatiblePluginsException: Binary incompatibility in plugins detected.
[error] Note that conflicts were resolved for some dependencies:
[error] 	org.scala-lang.modules:scala-parser-combinators_2.12
[error] 	org.slf4j:slf4j-api
[error] 	org.scala-lang.modules:scala-xml_2.12
```

**Comment by seratch** [comment]
I don’t have time to check until tomorrow. The following one is a working example. Checking it may be of help to you. 

https://github.com/skinny-framework/skinny-framework/tree/master/skinny-blank-app

If I see any bugs in this sbt plugin, I will work on it.

**Comment by ngocdaothanh** [comment]
Thanks!

I see that the README doesn't mention `scalateSettings` at the section for build.sbt. After I add it, sbt-scalate-precompiler works as expected.

So please improve README to mention `scalateSettings` for build.sbt.

**Comment by seratch** [comment]
I got it. Will do. Thanks!

**Comment by seratch** [comment]
I've updated README to have `scalateSettings` in `build.sbt` by https://github.com/scalate/sbt-scalate-precompiler/commit/860b6faf2f50713e47738d534dcfec51d43c596c .

Thank you for your feedback. Let me close this issue.
