### ISSUE TITLE
cannot resolving dependency on Sonatype repository

### ISSUE THREAD

**Issue by Parabellum1905y** [scalate/sbt-scalate-precompiler#5]
Hello, jar not  found on Sonatype:

==== Sonatype OSS Snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/org/scalatra/scalate/sbt-scalate-precompiler_2.12_1.0/1.8.0.1/sbt-scalate-precompiler-1.8.0.1.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scalatra.scalate#sbt-scalate-precompiler;1.8.0.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

**Comment by magnolia-k** [comment]
Is it because the sbt 1.0 compatible version has not yet been released?

**Comment by magnolia-k** [comment]
There are now plugins released that support SBT 1.X, so this issue should be resolved.
