### ISSUE TITLE
Update import in README

### ISSUE THREAD

**Issue by ngocdaothanh** [scalate/sbt-scalate-precompiler#7]
The README currently mentions:

```
import ScalateKeys._

scalateSettings
...
```

But there's error with that. It should be:

```
import org.fusesource.scalate.ScalatePlugin._
```

**Comment by seratch** [comment]
You’re right. I’ve fixed that. Thanks.

**Comment by ngocdaothanh** [comment]
Just to confirm, with the latest version, now we don't need to include `scalateSettings` any more because we are using the autoimport mechanism of SBT 1.x?

**Comment by seratch** [comment]
Yes, exactly.
